name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    environment: cypress

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          VITE_CYPRESS_USER: ${{ secrets.VITE_CYPRESS_USER }}
          VITE_CYPRESS_EMAIL: ${{ secrets.VITE_CYPRESS_EMAIL }}
          VITE_CYPRESS_PASSWORD: ${{ secrets.VITE_CYPRESS_PASSWORD }}
        with:
          browser: chrome
          start: npm run preview
          wait-on: "http://localhost:4173"
